services:
  - type: web
    name: employee-system
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn Employee_System.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "employee-system.onrender.com"
      - key: DATABASE_URL # This will now be read from your Render dashboard
        sync: false
      - key: SUPABASE_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_BUCKET_NAME
        sync: false
      - key: SUPABASE_ENDPOINT_URL
        sync: false
      - key: SUPABASE_REGION
        value: "us-east-1"
