# Generated by Django 5.2.5 on 2025-09-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('vacation', 'Vacation Leave')], max_length=20),
        ),
    ]
