# Generated by Django 5.2.5 on 2025-08-25 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=datetime.date(2025, 8, 25)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(),
        ),
    ]
