# Generated by Django 5.2.5 on 2025-08-30 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for Google Authenticator', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
