# Generated by Django 5.2.5 on 2025-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_totp_secret_alter_employee_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
