# Generated by Django 5.2.5 on 2025-08-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_last_login_ip_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
