# Generated by Django 5.2.5 on 2025-09-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employee_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_seen',
        ),
    ]
