# Generated by Django 5.2.5 on 2025-09-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_employee_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.CharField(default=0),
        ),
    ]
