# Generated by Django 5.2.5 on 2025-09-14 12:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='blank-profile-picture', max_length=255, verbose_name='image'),
        ),
    ]
