# Generated by Django 5.2.5 on 2025-09-15 14:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[accounts.models.gmail_only_validator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(max_length=20, validators=[accounts.models.philippine_phone_validator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[accounts.models.philippine_phone_validator]),
        ),
    ]
