# Generated by Django 5.2.5 on 2025-09-15 15:13

import accounts.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='blank-profile-picture', max_length=255, validators=[accounts.models.image_file_validator], verbose_name='image'),
        ),
    ]
