# Generated by Django 5.2.5 on 2025-09-17 14:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employee-photos/blank-profile-picture.png', null=True, upload_to='employee-photos/', validators=[accounts.models.image_file_validator]),
        ),
    ]
