# Generated by Django 5.2.5 on 2025-09-18 12:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=accounts.models.get_current_date),
        ),
    ]
