# Generated by Django 5.2.5 on 2025-09-22 07:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_employee_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.employee_photo_upload_path, validators=[accounts.models.image_file_validator]),
        ),
    ]
