# Generated by Django 5.2.5 on 2025-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_schedule',
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Regular hourly wage rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overtime hourly rate (auto-calculated as hourly_rate + 0.5)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Expected weekly work hours', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(default='17:00', help_text='Standard work end time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(default='08:00', help_text='Standard work start time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(blank=True, help_text='Annual salary', null=True),
        ),
    ]
