# Generated by Django 5.2.5 on 2025-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(blank=True, help_text='Weekly salary', null=True),
        ),
    ]
