# Generated by Django 5.2.5 on 2025-09-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paychecknotification',
            name='notification_type',
        ),
    ]
