# Generated by Django 5.2.5 on 2025-09-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecknotification',
            name='notification_type',
            field=models.CharField(default='paycheck', max_length=50),
        ),
    ]
