# Generated by Django 5.2.5 on 2025-09-23 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecknotification',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paychecknotification',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paychecknotification',
            unique_together={('employee', 'week_start_date', 'week_end_date', 'notification_type')},
        ),
    ]
