# Generated by Django 5.2.5 on 2025-10-02 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated overtime hours for this day', max_digits=5)),
                ('overtime_approved', models.BooleanField(default=False, help_text='Whether overtime has been approved by admin')),
                ('overtime_rejected', models.BooleanField(default=False, help_text='Whether overtime has been rejected by admin')),
                ('overtime_approval_date', models.DateTimeField(blank=True, help_text='When overtime was approved/rejected', null=True)),
                ('overtime_notes', models.TextField(blank=True, help_text='Admin notes about overtime approval/rejection')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('overtime_approved_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected overtime', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
