# Generated by Django 5.2.5 on 2025-09-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in_time',
            new_name='time_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_out_time',
            new_name='time_out',
        ),
    ]
