# Generated by Django 5.2.5 on 2025-09-22 13:42

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=attendance.models.get_current_date),
        ),
    ]
