# Generated by Django 5.2.5 on 2025-09-23 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_approval_date',
            field=models.DateTimeField(blank=True, help_text='When overtime was approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_approved',
            field=models.BooleanField(default=False, help_text='Whether overtime has been approved by admin'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected overtime', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated overtime hours for this day', max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_notes',
            field=models.TextField(blank=True, help_text='Admin notes about overtime approval/rejection'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_rejected',
            field=models.BooleanField(default=False, help_text='Whether overtime has been rejected by admin'),
        ),
    ]
