# Generated by Django 5.2.5 on 2025-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
